name: 'Realese build and deploy'

on:
   release:
      types: [released]
jobs:
   build:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [22.14.0]
      steps:
         - name: 'Checkout repo'
           uses: actions/checkout@v4
         - name: Install pnpm
           uses: pnpm/action-setup@v4
           with:
              version: 10
         - name: 'Dependencies install'
           run: pnpm install --frozen-lockfile
         - name: 'Init prisma'
           run: npx prisma generate
         - name: 'Build project'
           run: pnpm run build
         - name: Коммит сборки в ветку release
           run: |
              git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git fetch origin
                git checkout -b release origin/release || git checkout release
                git pull origin release
                cp -r dist/* .
                git add .
                git diff --staged --quiet || git commit -m "Deploy build for release ${{ github.event.release.tag_name }}" || true
                git push origin release || true
   deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
         - name: Deploy to Server
           uses: appleboy/ssh-action@v1.0.3
           with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USER }}
              key: ${{ secrets.SSH_KEY }}
              script: |
                 cd /home/web/projects/dice-bot
                 source ./update.sh
